version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  app:
    build: .
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes_from:
      - appdata
    links:
      - "mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8081:80
    environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root

  mailhog:
    image: mailhog/mailhog
    ports:
        - "8025:8025"

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  appdata:
    image: tianon/true
    volumes:
      - ".:/workspace"
